### ISSUE TITLE
Verify Results

### ISSUE THREAD

**Issue by heussd** [heussd/loddwhbench#10]
Verify the results of the `query()` method. It should be noted if results differ, and not why / how they differ. 

The updated `QueryResult`-Object might be of use, resp. the newly developed `equal()`/`hashCode()` method. Note the evaluation as new table, for example:

| QueryScenario | Impl1 | Impl2 | Impl3 | ... |
| --- | --- | --- | --- | --- |
| DELETE_LOW_SELECTIVITY_PAPER_MEDIUM | QR.hashCode | QR.hashCode | QR.hashCode | QR.hashCode |

**Comment by prototype2201** [comment]
QueryResults are now being compared over hashCode() in a new report, see results.md.
