### ISSUE TITLE
Retrieve actual BenchmarkObject.title from given Dataset

### ISSUE THREAD

**Issue by heussd** [heussd/loddwhbench#21]
`new BenchmarkObject(Virtuoso 1.000", new Virtuoso("hebis_1000_test", Dataset.hebis_tiny_rdf,....`  - the 1.000 should be taken from the Dataset name.

**Comment by prototype2201** [comment]
Use the enum-name as title, for example "Virtuoso hebis_1000_rdf", implicit.
