### ISSUE TITLE
Define Query Executions & Time Aggreations

### ISSUE THREAD

**Issue by heussd** [heussd/loddwhbench#23]

**Comment by heussd** [comment]
# For each individual Database-Impl

Output Format for `QueryScenario.isReadOnly = true`: Every query is executed 3 times (should be configurable via `Config.class`). Output:

| QueryScenario | Phase | First Time | Average Time | Min Time | Max Time |
| --- | --- | --- | --- | --- | --- |
| ENTITY_RETRIEVAL_BY_ID_CASE1 | Prepare | 122 ms | - | - | - |
| ENTITY_RETRIEVAL_BY_ID_CASE1 | Query | 20 ms | 12 ms | 2 ms | 300 ms |

Output Format for `QueryScenario.isReadOnly = false`:

| QueryScenario | Phase | One Time | Average | Min | Max |
| --- | --- | --- | --- | --- | --- |
| DELETE_LOW_SELECTIVITY_PAPER_MEDIUM | Prepare | 122 ms | - | - | - |
| DELETE_LOW_SELECTIVITY_PAPER_MEDIUM | Query | 12 ms | - | - | - |

# Sum-Up report at the end:

Take Average values, mark lowest score in each row

| QueryScenario | Phase | Impl1 | Impl2 | Impl3 | ... |
| --- | --- | --- | --- | --- | --- |
| DELETE_LOW_SELECTIVITY_PAPER_MEDIUM | Prepare | 122 ms | 100ms | **90ms** | 122ms |
| DELETE_LOW_SELECTIVITY_PAPER_MEDIUM | Query | 122 ms | 100ms | **90ms** | 122ms |

**Comment by prototype2201** [comment]
See changes in updated results.md
