### ISSUE TITLE
Introduce TestSeries

### ISSUE THREAD

**Issue by heussd** [heussd/loddwhbench#29]
The three test series are:

"Tiny" - hebis_1000_rdf.gz
"Small" - hebis_100000_rdf.gz
"Medium" - hebis-10147116-13050073.rdf.gz + hebis-29873806-36057474.rdf
"Large" - All hebis-_-_.rdf.gz

**Comment by prototype2201** [comment]
Usage of TestSeries is implemented, but for running the benchmark further actions are necessary as load() is now possibly called multiple times. For Virtuoso and MongoDB it seems to be ok, but at least SQLite and PostgreSql are generating tables in load(), which let the benchmark crash at the second load(). Generating the tables should be executed in setUp(). But that may be not the only problem: SQLite is setting a "lastLoadedDataset" in load(), which is then used in prepare() of some scenarios. It may be that it is not the expected lastLoadedDataset in the moment of execution of the prepare().
